/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package window_cleaner;

import exceptions.HouseAlreadyExistsException;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author badan
 */
public class AddHouseWindow extends javax.swing.JFrame {

    WindowController controller;
    /**
     * Creates new form AddHouseWindow
     * @param controller
     */
    public AddHouseWindow(WindowController controller) {
        this.controller = controller;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addHouseLabel = new javax.swing.JLabel();
        addHouseTextField = new javax.swing.JTextField();
        addHouseSubmitButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        addHouseLabel.setText("House:");

        addHouseTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addHouseTextFieldActionPerformed(evt);
            }
        });

        addHouseSubmitButton.setText("Add House");
        addHouseSubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addHouseSubmitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addHouseLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addHouseTextField))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 177, Short.MAX_VALUE)
                        .addComponent(addHouseSubmitButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addHouseLabel)
                    .addComponent(addHouseTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(addHouseSubmitButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addHouseTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addHouseTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addHouseTextFieldActionPerformed

    private void addHouseSubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addHouseSubmitButtonActionPerformed
        try {
            String houseName = addHouseTextField.getText();
            if(houseName.equals("")){
                JOptionPane.showMessageDialog(null, "Fill the house number first", "Ops", JOptionPane.INFORMATION_MESSAGE);                
            } else {
                controller.addHouse(houseName);
                this.dispose();
            }
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "Something went wrong! Pls restart the program", "Ops", JOptionPane.INFORMATION_MESSAGE);
        } catch (HouseAlreadyExistsException ex) {
            JOptionPane.showMessageDialog(null, "This house alredy exists", "Ops", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_addHouseSubmitButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addHouseLabel;
    private javax.swing.JButton addHouseSubmitButton;
    private javax.swing.JTextField addHouseTextField;
    // End of variables declaration//GEN-END:variables
}
